###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"john@example.com",
    "password":"admin123"
}

### Create Vehiculo
POST http://localhost:3000/vehiculo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2ODM1OTAsImV4cCI6MTc1NzY4Mzg5MH0.Aqkn5Bl6xHklC8N8_wZk4OWHLPptgMWmk7TSWsYC1Oo

{
    "patente":"BXVP-30",
    "capacidad":20000,
    "odometro":13980,
    "estado": "disponible"
}

### alls  Vehiculo
GET http://localhost:3000/vehiculo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2ODM1OTAsImV4cCI6MTc1NzY4Mzg5MH0.Aqkn5Bl6xHklC8N8_wZk4OWHLPptgMWmk7TSWsYC1Oo

### alls  Vehiculo
GET http://localhost:3000/vehiculo/BXVP-39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTU5ODQsImV4cCI6MTc1NzU1NjI4NH0.6VAJydqcz1t0WLEMi5fJIB7r7xskQawsoPHI-BOvhLk

### patch Vehiculo
PATCH  http://localhost:3000/vehiculo/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2ODM1OTAsImV4cCI6MTc1NzY4Mzg5MH0.Aqkn5Bl6xHklC8N8_wZk4OWHLPptgMWmk7TSWsYC1Oo

{
    "estado":"en_mantenimiento"
}

### Eliminar Vehiculo
DELETE   http://localhost:3000/vehiculo/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2ODM1OTAsImV4cCI6MTc1NzY4Mzg5MH0.Aqkn5Bl6xHklC8N8_wZk4OWHLPptgMWmk7TSWsYC1Oo


### patch Vehiculo Estado
POST  http://localhost:3000/vehiculo/1/documentos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2ODM1OTAsImV4cCI6MTc1NzY4Mzg5MH0.Aqkn5Bl6xHklC8N8_wZk4OWHLPptgMWmk7TSWsYC1Oo

{
    "tipo": "pdf",
    "url": "local:asda",
    "descripcion": "documento" 
}


