###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"john@example.com",
    "password":"admin123"
}

###TODO No funciona
POST http://localhost:3000/solicitud-compra
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2MDQyMzEsImV4cCI6MTc1NzYwNDUzMX0.C1iPDbhf1jH7BJiA8P2yu5LdjGRz-17TPEp5xxn-6WM

{
  "monto": 12000,
  
}

###ç
GET http://localhost:3000/solicitud-compra
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2MDQ1ODksImV4cCI6MTc1NzYwNDg4OX0.N4acp2xyb9tI8w3xaET7qqMTDcslbB0SMKPuyr7m248


