// Datos mínimos para el modo demo del frontend web
// Nota: mantener liviano, solo lo necesario para navegar y mostrar ejemplos

export const demoNowIso = () => new Date().toISOString();

export const demoUser = {
  id: 999,
  username: "demo",
  email: "demo@example.com",
  firstName: "Demo",
  lastName: "User",
  active: true,
  roleAssignments: [
    { role: "Lector", specialty: "DRIVER", isActive: true },
  ],
};

export const demoNotifications = {
  items: [
    {
      id: 1,
      title: "Bienvenido al modo Demo",
      message: "Explora libremente. Usa el botón ‘Iniciar tour’ en la barra superior.",
      priority: "normal",
      createdAt: demoNowIso(),
      scheduledAt: null,
      pinned: true,
      roles: [],
      areas: [],
      type: "GENERAL",
      createdBy: { id: 1, username: "system" },
      readBy: [],
    },
    {
      id: 2,
      title: "Mantenimiento programado",
      message: "Se realizará mantenimiento del sistema el sábado a las 22:00.",
      priority: "high",
      createdAt: demoNowIso(),
      scheduledAt: null,
      pinned: false,
      roles: ["ADMIN"],
      areas: [],
      type: "ALERT",
      createdBy: { id: 1, username: "sistemas" },
      readBy: [],
    },
    {
      id: 3,
      title: "Nueva ruta piloto",
      message: "Se habilitó la ruta piloto R-006 para pruebas.",
      priority: "normal",
      createdAt: demoNowIso(),
      scheduledAt: null,
      pinned: false,
      roles: [],
      areas: ["Transporte"],
      type: "INFO",
      createdBy: { id: 2, username: "operaciones" },
      readBy: [],
    },
    {
      id: 4,
      title: "Capacitación de seguridad",
      message: "Recordatorio: capacitación obligatoria el próximo lunes.",
      priority: "low",
      createdAt: demoNowIso(),
      scheduledAt: null,
      pinned: false,
      roles: ["DRIVER"],
      areas: [],
      type: "REMINDER",
      createdBy: { id: 3, username: "rrhh" },
      readBy: [],
    },
    {
      id: 5,
      title: "Aviso programado",
      message: "Revisión de extintores en sector B.",
      priority: "normal",
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      scheduledAt: new Date(Date.now() + 86400000).toISOString(),
      pinned: false,
      roles: [],
      areas: ["Bodegas"],
      type: "SCHEDULED",
      createdBy: { id: 4, username: "prevencion" },
      readBy: [],
    },
  ],
  total: 5,
  page: 1,
  pageSize: 20,
};

export const demoVehicles = [
  {
    id: 101,
    patente: "ABCZ10",
    marca: "Volvo",
    modelo: "FH",
    tipo: "Camión",
    capacidad: 20000,
    odometro: 123456,
    estado: "disponible",
    areaAsignada: "Transporte",
    codigo: "V-101",
    conductorId: 999,
    lastMaintenanceDate: new Date(),
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 102,
    patente: "JKLZ20",
    marca: "Mercedes",
    modelo: "Actros",
    tipo: "Camión",
    capacidad: 18000,
    odometro: 654321,
    estado: "en_mantenimiento",
    areaAsignada: "Transporte",
    codigo: "V-102",
    conductorId: 999,
    lastMaintenanceDate: new Date(),
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 103,
    patente: "MNOP30",
    marca: "Scania",
    modelo: "R500",
    tipo: "Camión",
    capacidad: 22000,
    odometro: 223450,
    estado: "en_uso",
    areaAsignada: "Transporte",
    codigo: "V-103",
    conductorId: 999,
    lastMaintenanceDate: new Date(Date.now() - 15 * 24 * 3600 * 1000),
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 104,
    patente: "QRST40",
    marca: "Iveco",
    modelo: "Stralis",
    tipo: "Camión",
    capacidad: 16000,
    odometro: 83450,
    estado: "inactivo",
    areaAsignada: "Mantenimiento",
    codigo: "V-104",
    conductorId: null,
    lastMaintenanceDate: new Date(Date.now() - 60 * 24 * 3600 * 1000),
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 105,
    patente: "UVWX50",
    marca: "Volvo",
    modelo: "FM",
    tipo: "Camión",
    capacidad: 19000,
    odometro: 145600,
    estado: "disponible",
    areaAsignada: "Transporte",
    codigo: "V-105",
    conductorId: 999,
    lastMaintenanceDate: new Date(Date.now() - 5 * 24 * 3600 * 1000),
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
];

export const demoFuelSummary = demoVehicles.map((v, idx) => ({
  ...v,
  fuelLogs: [
    {
      id: idx * 10 + 1,
      date: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
      liters: 80 + (idx % 5) * 5,
      cost: 90000 + (idx % 5) * 5000,
      odometer: v.odometro - 1200,
      driver: { id: demoUser.id, username: demoUser.username },
      invoiceUrl: null,
      createdAt: demoNowIso(),
    },
    {
      id: idx * 10 + 2,
      date: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
      liters: 100 + (idx % 5) * 7,
      cost: 120000 + (idx % 5) * 6000,
      odometer: v.odometro - 600,
      driver: { id: demoUser.id, username: demoUser.username },
      invoiceUrl: null,
      createdAt: demoNowIso(),
    },
    {
      id: idx * 10 + 3,
      date: demoNowIso(),
      liters: 110 + (idx % 5) * 6,
      cost: 135000 + (idx % 5) * 7000,
      odometer: v.odometro,
      driver: { id: demoUser.id, username: demoUser.username },
      invoiceUrl: null,
      createdAt: demoNowIso(),
    },
  ],
}));

import type { VehicleWithFuelHistory } from "./fuelApi";

export const demoFuelHistoryByVehicleId: Record<number, VehicleWithFuelHistory> = Object.fromEntries(
  demoFuelSummary.map((v) => [v.id, v as VehicleWithFuelHistory])
);

export const demoRoutesAssignments = {
  items: [
    {
      id: 201,
      truckId: 101,
      routeId: 301,
      driverId: demoUser.id,
      date: new Date().toISOString().slice(0, 10),
      status: "assigned",
      startTime: null,
      endTime: null,
      volumeLiters: 5000,
    },
    {
      id: 202,
      truckId: 102,
      routeId: 302,
      driverId: demoUser.id,
      date: new Date().toISOString().slice(0, 10),
      status: "in_progress",
      startTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
      endTime: null,
      volumeLiters: 4200,
    },
    {
      id: 203,
      truckId: 103,
      routeId: 303,
      driverId: demoUser.id,
      date: new Date(Date.now() - 24 * 3600 * 1000).toISOString().slice(0, 10),
      status: "completed",
      startTime: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
      endTime: new Date(Date.now() - 23 * 3600 * 1000).toISOString(),
      volumeLiters: 5100,
    },
  ],
  total: 3,
  page: 1,
  pageSize: 50,
};

// Rutas de transporte (mínimas para la vista de rutas)
export const demoTransportRoutes = [
  { id: 301, code: 'R-001', origin: 'Planta Norte', destination: 'Bodega Central', distanceKm: 120, frequency: 'Diaria', active: true, createdAt: demoNowIso(), updatedAt: demoNowIso() },
  { id: 302, code: 'R-002', origin: 'Planta Sur', destination: 'Sucursal 2', distanceKm: 85, frequency: 'Semanal', active: true, createdAt: demoNowIso(), updatedAt: demoNowIso() },
  { id: 303, code: 'R-003', origin: 'Bodega Central', destination: 'Cliente Z', distanceKm: 45, frequency: 'Eventual', active: false, createdAt: demoNowIso(), updatedAt: demoNowIso() },
  { id: 304, code: 'R-004', origin: 'Planta Oeste', destination: 'Sucursal 5', distanceKm: 60, frequency: 'Diaria', active: true, createdAt: demoNowIso(), updatedAt: demoNowIso() },
  { id: 305, code: 'R-005', origin: 'Sucursal 1', destination: 'Cliente A', distanceKm: 30, frequency: 'Diaria', active: true, createdAt: demoNowIso(), updatedAt: demoNowIso() },
  { id: 306, code: 'R-006', origin: 'Bodega Central', destination: 'Cliente Beta', distanceKm: 75, frequency: 'Semanal', active: true, createdAt: demoNowIso(), updatedAt: demoNowIso() },
];

export const demoWorkOrders = [
  {
    id: 401,
    vehiculoId: 102,
    tipo: "Preventivo",
    description: "Cambio de filtros y revisión general",
    estado: "abierta" as const,
    repuestos: ["Filtro de aceite", "Filtro de aire"],
    tareas: ["Revisión de niveles", "Ajuste general"],
    responsableId: 1001,
    scheduledDate: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
    estimatedCost: 120000,
    observations: "Prioridad media",
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 402,
    vehiculoId: 103,
    tipo: "Correctivo",
    description: "Reparación de fuga hidráulica",
    estado: "en_progreso" as const,
    repuestos: ["Manguera hidráulica"],
    tareas: ["Diagnóstico", "Reemplazo de manguera"],
    responsableId: 1001,
    scheduledDate: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    estimatedCost: 280000,
    observations: "Unidad fuera de servicio",
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
  {
    id: 403,
    vehiculoId: 101,
    tipo: "Preventivo",
    description: "Ajuste de frenos",
    estado: "completado" as const,
    repuestos: ["Pastillas de freno"],
    tareas: ["Cambio de pastillas", "Prueba de rodado"],
    responsableId: 1001,
    scheduledDate: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    estimatedCost: 150000,
    observations: "OK QA",
    createdAt: demoNowIso(),
    updatedAt: demoNowIso(),
  },
];

export const demoWorkshopOverview = {
  workOrders: {
    items: demoWorkOrders,
    total: demoWorkOrders.length,
    page: 1,
    pageSize: 10,
  },
  vehicles: {
    items: demoVehicles,
    total: demoVehicles.length,
    page: 1,
    pageSize: 10,
  },
  users: {
    items: [demoUser],
    total: 1,
    page: 1,
    pageSize: 10,
  },
  mechanics: {
    items: [],
    total: 0,
    page: 1,
    pageSize: 10,
  },
};

export const demoTickets = {
  items: [
    {
      id: 501,
      title: "Solicito acceso a módulo de KPIs",
      description: "No veo el tab de KPIs",
      category: "Acceso",
      priority: "Media",
      status: "Pendiente",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: demoUser.id, username: demoUser.username },
      assignedTo: null,
      recipientArea: ["Operaciones"],
      recipientRole: ["Supervisor"],
      assignedUserConfirmation: null,
      requestingUserConfirmation: null,
      tags: ["helpdesk", "kpis"],
    },
    {
      id: 502,
      title: "Error en creación de rutas",
      description: "El formulario muestra un error 500 al guardar.",
      category: "Bug",
      priority: "Alta",
      status: "EnProgreso",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: 1002, username: "juan" },
      assignedTo: { id: demoUser.id, username: demoUser.username },
      recipientArea: ["Transporte"],
      recipientRole: ["Especialista"],
      assignedUserConfirmation: true,
      requestingUserConfirmation: null,
      tags: ["rutas", "bug"],
    },
    {
      id: 503,
      title: "Mejora en reporte de combustible",
      description: "Agregar exportación a CSV en el listado de cargas.",
      category: "Mejora",
      priority: "Baja",
      status: "Resuelto",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: 1001, username: "maria" },
      assignedTo: { id: 1002, username: "juan" },
      recipientArea: ["Transporte"],
      recipientRole: ["Supervisor", "Especialista"],
      assignedUserConfirmation: true,
      requestingUserConfirmation: true,
      tags: ["combustible", "mejora"],
    },
    {
      id: 504,
      title: "No puedo adjuntar imágenes en incidentes",
      description: "El botón de adjuntar no abre el selector.",
      category: "Soporte",
      priority: "Urgente",
      status: "Pendiente",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: demoUser.id, username: demoUser.username },
      assignedTo: null,
      recipientArea: ["Seguridad"],
      recipientRole: ["Especialista"],
      assignedUserConfirmation: null,
      requestingUserConfirmation: null,
      tags: ["incidentes", "adjuntos"],
    },
    {
      id: 505,
      title: "Actualizar manual de usuario",
      description: "Faltan secciones para el módulo de limpieza.",
      category: "Documentación",
      priority: "Media",
      status: "EnProgreso",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: 1001, username: "maria" },
      assignedTo: { id: demoUser.id, username: demoUser.username },
      recipientArea: ["Limpieza"],
      recipientRole: ["Trabajador"],
      assignedUserConfirmation: true,
      requestingUserConfirmation: null,
      tags: ["docs", "limpieza"],
    },
    {
      id: 506,
      title: "Cerrar ticket antiguo de prueba",
      description: "Se resolvió con la versión 1.2.3.",
      category: "Mantenimiento",
      priority: "Baja",
      status: "Cerrado",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
      createdBy: { id: 1002, username: "juan" },
      assignedTo: null,
      recipientArea: ["TI"],
      recipientRole: ["Admin"],
      assignedUserConfirmation: null,
      requestingUserConfirmation: true,
      tags: ["cierre", "prueba"],
    },
  ],
  total: 6,
  page: 1,
  pageSize: 50,
};

export const demoCleaning = {
  items: [
    {
      id: 601,
      date: demoNowIso(),
      area: "Bodegas",
      responsibleStaff: "Equipo A",
      tasks: ["Barrido", "Desinfección"],
      issues: [],
      timeSpent: 120,
      status: "COMPLETED",
      observations: "Sin novedades",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
    },
    {
      id: 602,
      date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      area: "Patio de Maniobras",
      responsibleStaff: "Equipo B",
      tasks: ["Barrido"],
      issues: ["Aceite en zona norte"],
      timeSpent: 90,
      status: "COMPLETED",
      observations: "Se programó limpieza profunda",
      createdAt: demoNowIso(),
      updatedAt: demoNowIso(),
    },
  ],
  total: 2,
  page: 1,
  pageSize: 20,
};

export const demoIncidents = {
  items: [
    {
      id: 701,
      title: "Retraso por tráfico",
      description: "Obras en la ruta principal",
      area: "Transporte",
      type: "TRAFFIC_DELAY",
      severity: "LOW",
      status: "REPORTED",
      location: { latitude: -33.45, longitude: -70.66, address: "Av. Demo 123" },
      photos: [],
      reportedById: demoUser.id,
      reportedAt: demoNowIso(),
      updatedAt: demoNowIso(),
    },
    {
      id: 702,
      title: "Falla mecánica",
      description: "Pérdida de potencia en subida",
      area: "Transporte",
      type: "BREAKDOWN",
      severity: "MEDIUM",
      status: "IN_PROGRESS",
      location: { latitude: -33.48, longitude: -70.62, address: "Ruta 5 KM 24" },
      photos: [],
      reportedById: demoUser.id,
      reportedAt: demoNowIso(),
      updatedAt: demoNowIso(),
    },
    {
      id: 703,
      title: "Incidente de seguridad",
      description: "Casi colisión en cruce",
      area: "Transporte",
      type: "ACCIDENT",
      severity: "HIGH",
      status: "RESOLVED",
      location: { latitude: -33.5, longitude: -70.7, address: "Av. Central con Los Robles" },
      photos: [],
      reportedById: demoUser.id,
      reportedAt: demoNowIso(),
      updatedAt: demoNowIso(),
    },
  ],
  total: 3,
  page: 1,
  pageSize: 20,
};

// Obras Civiles (semillas compatibles con types/CivilWork.ts)
export const demoCivilWorks = {
  items: [
    {
      id: 801,
      project: "Canalización perimetral",
      location: "Sector 5",
      startDate: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 10 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "CONSTRUCTION" as const,
      tasks: [
        { name: "Levantamiento topográfico", completed: true },
        { name: "Excavación de zanja", completed: true },
        { name: "Instalación de tuberías", completed: false },
        { name: "Relleno y compactación", completed: false },
      ],
      progress: 50,
      status: "IN_PROGRESS" as const,
      observations: "Avance estable, coordinar con suministro.",
      issues: ["Retraso en entrega de materiales"],
      photos: [],
      createdById: demoUser.id,
      responsibleStaffUsernames: ["maria", "juan"],
      materialsUsed: ["Tubería PVC 160mm", "Aridos"],
    },
    {
      id: 802,
      project: "Mejora de drenajes secundarios",
      location: "Sector 2",
      startDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 20 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "REPAIR" as const,
      tasks: [
        { name: "Despeje y limpieza", completed: true },
        { name: "Rectificación de pendientes", completed: false },
        { name: "Revestimiento", completed: false },
      ],
      progress: 33,
      status: "IN_PROGRESS" as const,
      observations: "Pendiente evaluación de riesgos por lluvias.",
      issues: [],
      photos: [],
      createdById: 1002,
      responsibleStaffUsernames: ["juan"],
      materialsUsed: ["Cemento", "Malla ACMA"],
    },
    {
      id: 803,
      project: "Pavimentación acceso principal",
      location: "Acceso Principal",
      startDate: new Date(Date.now() - 60 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
      workType: "MAINTENANCE" as const,
      tasks: [
        { name: "Preparación de base", completed: true },
        { name: "Colocación de capa asfáltica", completed: true },
        { name: "Sellado de juntas", completed: true },
      ],
      progress: 100,
      status: "COMPLETED" as const,
      observations: "Recepción conforme.",
      issues: [],
      photos: [],
      createdById: demoUser.id,
      responsibleStaffUsernames: ["maria"],
      materialsUsed: ["Asfalto", "Sellante"],
    },
    {
      id: 804,
      project: "Inspección estructural de pasarela",
      location: "Sector 7",
      startDate: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 2 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "INSPECTION" as const,
      tasks: [
        { name: "Revisión visual", completed: true },
        { name: "Informe técnico", completed: false },
      ],
      progress: 50,
      status: "IN_PROGRESS" as const,
      observations: "Sin hallazgos críticos preliminares.",
      issues: [],
      photos: [],
      createdById: 1001,
      responsibleStaffUsernames: ["maria", "demo"],
      materialsUsed: [],
    },
    {
      id: 805,
      project: "Refuerzo de talud norte",
      location: "Talud Norte",
      startDate: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 8 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "REPAIR" as const,
      tasks: [
        { name: "Hincado de anclajes", completed: false },
        { name: "Malla metálica", completed: false },
        { name: "Proyección de shotcrete", completed: false },
      ],
      progress: 0,
      status: "PENDING" as const,
      observations: "En espera de aprobación ambiental.",
      issues: ["Permisos en trámite"],
      photos: [],
      createdById: 1002,
      responsibleStaffUsernames: ["juan"],
      materialsUsed: ["Anclajes", "Malla", "Cemento"],
    },
    {
      id: 806,
      project: "Canal de contención sector Este",
      location: "Sector Este",
      startDate: new Date(Date.now() - 25 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "CONSTRUCTION" as const,
      tasks: [
        { name: "Topografía", completed: true },
        { name: "Movimiento de tierras", completed: true },
        { name: "Hormigonado", completed: true },
        { name: "Acabados", completed: false },
      ],
      progress: 75,
      status: "IN_PROGRESS" as const,
      observations: "Restan acabados y limpieza final.",
      issues: [],
      photos: [],
      createdById: demoUser.id,
      responsibleStaffUsernames: ["demo"],
      materialsUsed: ["Hormigón H20", "Acero 8mm"],
    },
    {
      id: 807,
      project: "Mantenimiento de alcantarillas internas",
      location: "Red interna",
      startDate: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() + 1 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "MAINTENANCE" as const,
      tasks: [
        { name: "Limpieza", completed: true },
        { name: "Desobstrucción", completed: true },
        { name: "Revisión final", completed: false },
      ],
      progress: 66,
      status: "IN_PROGRESS" as const,
      observations: "Cierre esperado mañana.",
      issues: [],
      photos: [],
      createdById: 1001,
      responsibleStaffUsernames: ["maria"],
      materialsUsed: ["Herramientas manuales"],
    },
    {
      id: 808,
      project: "Control de erosión en zona sur",
      location: "Zona Sur",
      startDate: new Date(Date.now() - 40 * 24 * 3600 * 1000).toISOString(),
      estimatedEndDate: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
      actualEndDate: null,
      workType: "INSPECTION" as const,
      tasks: [
        { name: "Monitoreo de taludes", completed: true },
        { name: "Informe mensual", completed: true },
      ],
      progress: 100,
      status: "COMPLETED" as const,
      observations: "Programa cumplido, seguimiento trimestral.",
      issues: [],
      photos: [],
      createdById: 1002,
      responsibleStaffUsernames: ["juan"],
      materialsUsed: [],
    },
  ],
  total: 8,
  page: 1,
  pageSize: 50,
};

export const demoUsersList = {
  items: [
    demoUser,
    { id: 1001, username: "maria", email: "maria@example.com", firstName: "María", lastName: "González", active: true, roleAssignments: [{ role: "Operador", specialty: "DRIVER", isActive: true }] },
    { id: 1002, username: "juan", email: "juan@example.com", firstName: "Juan", lastName: "Pérez", active: true, roleAssignments: [{ role: "Supervisor", specialty: "ADMIN", isActive: true }] },
  ],
  total: 3,
  page: 1,
  pageSize: 200,
};
