import React, { createContext, useContext, ReactNode, useState, useEffect, useMemo, useCallback } from 'react';

// Tipado explícito para evitar TS7053 al indexar con string
export type Languages = 'en' | 'es' | 'pt' | 'fr' | 'de' | 'it';

type LanguageContextType = {
  t: (key: string) => string;
  language: Languages;
  setLanguage: React.Dispatch<React.SetStateAction<Languages>>;
};

const englishTranslations: Record<string, string> = {
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.description': 'Description',
    'common.priority': 'Priority',
    'common.category': 'Category',
    'common.loading': 'Loading...',
    'common.submit': 'Submit',
    'common.close': 'Close',
    'common.view': 'View',
    'common.details': 'Details',
    'common.viewDetails': 'View Details',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.role': 'Role',
    'common.area': 'Area',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.all': 'All',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
  'common.saving': 'Saving…',
  'common.creating': 'Creating…',
  'common.title': 'Title',
    
    // Login
    'login.title': 'Login',
    'login.subtitle': 'Business Management System',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing In...',
    'login.demoAccounts': 'Demo Accounts',
    'login.invalidCredentials': 'Invalid credentials',
    
    // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.inventory': 'Workshop Inventory',
  'nav.itInventory': 'IT Inventory',
    'nav.tripReports': 'Trip Reports',
    'nav.routeManagement': 'Route Management',
    'nav.fleetRegistry': 'Fleet Registry',
    'nav.maintenance': 'Maintenance',
    'nav.cleaningReports': 'Cleaning Reports',
    'nav.civilWorks': 'Civil Works',
    'nav.tickets': 'Ticket System',
  'nav.notifications': 'Notifications',
  'nav.fuel': 'Fuel',
  'nav.routes': 'Routes',
  'nav.assignments': 'Route Assignments',
  'nav.incidents': 'Incidents',
    'nav.userManagement': 'User Management',
  'nav.bukUsers': 'Buk Users',
    'nav.logout': 'Logout',
  'sidebar.logout': 'Log Out',
  'sidebar.sessionActive': 'Active session',
  'sidebar.brandSubtitle': 'Operations',

    // Buk integration
    'buk.title': 'Buk directory',
    'buk.description': 'Real-time user list synced from Buk through n8n.',
    'buk.refresh': 'Refresh data',
    'buk.total': 'Total users',
    'buk.empty': 'No Buk users available yet.',
    'buk.error': 'Error loading Buk users',
    'buk.columns.id': 'ID',
    'buk.columns.name': 'Name',
    'buk.columns.email': 'Email',
    'buk.columns.personId': 'Person ID',
    'buk.columns.status': 'Status',
    'buk.endpointLabel': 'Endpoint',
    
    // Dashboard
    'dashboard.welcome': 'Welcome',
    
    // Tickets
    'tickets.title': 'Ticket System',
    'tickets.subtitle': 'Manage support requests and task tracking',
    'tickets.newTicket': 'New Ticket',
    'tickets.createNew': 'Create New Ticket',
    'tickets.submitRequest': 'Submit a new support request or ticket',
    'tickets.title_field': 'Title',
    'tickets.category': 'Category',
    'tickets.priority': 'Priority',
    'tickets.description': 'Description',
    'tickets.attachments': 'Attachments',
    'tickets.totalTickets': 'Total Tickets',
    'tickets.pending': 'Pending',
    'tickets.inProgress': 'In Progress',
    'tickets.resolved': 'Resolved',
  // Tickets - extended
  'tickets.helpdesk': 'Help Desk',
  'tickets.header': 'Centralized corporate ticket tracking',
  'tickets.headerSub': 'Orchestrate internal requests, prioritize by criticality, and keep every area informed within the new collaborative panel.',
  'tickets.totalActiveSuffix': 'active ticket(s) total',
  'tickets.countSuffix': 'ticket(s)',
  'tickets.syncing': 'Syncing tickets…',
  'tickets.noResultsTitle': 'No tickets match current filters',
  'tickets.noResultsHint': 'Adjust filters or create a new ticket to get started.',
  'tickets.panel.filters': 'Filters Panel',
  'tickets.matchesSuffix': 'tickets match the criteria.',
  'tickets.noMatches': 'No matches, adjust criteria to continue.',
  'tickets.view.kanban': 'Kanban',
  'tickets.view.list': 'List',
  'tickets.filters.searchPlaceholder': 'Search by title, description or ID',
  'tickets.filters.reset': 'Reset filters',
  'tickets.unassigned': 'Unassigned',
  'tickets.noDate': 'No date',
  'tickets.review': 'Review',
  'tickets.emptyColumn': 'Nothing here yet.',
  'tickets.table.id': 'ID',
  'tickets.table.title': 'Title',
  'tickets.table.status': 'Status',
  'tickets.table.priority': 'Priority',
  'tickets.table.category': 'Category',
  'tickets.table.assigned': 'Assigned',
  'tickets.table.updated': 'Updated',
  'tickets.noTableItems': 'No tickets to show with current filters.',
  // Tickets - KPIs
  'tickets.kpis.inProgressSome': 'Coordinating assigned teams',
  'tickets.kpis.inProgressNone': 'No tickets in execution',
  'tickets.kpis.urgentLabel': 'Urgent',
  'tickets.kpis.urgentSome': 'Prioritize these critical cases',
  'tickets.kpis.urgentNone': 'No critical alerts',
  'tickets.kpis.totalInInboxSuffix': 'total in inbox',
  // Tickets - detail
  'tickets.detail.ticket': 'Ticket',
  'tickets.detail.status': 'Status',
  'tickets.detail.priority': 'Priority',
  'tickets.detail.category': 'Category',
  'tickets.detail.assignTo': 'Assign to',
  'tickets.detail.assign': 'Assign',
  'tickets.detail.assigning': 'Assigning…',
  'tickets.detail.createdBy': 'Created by',
  'tickets.detail.assignedTo': 'Assigned to',
  'tickets.detail.recipientAreas': 'Recipient areas',
  'tickets.detail.assignedUserConfirmation': 'Assigned user confirmation',
  'tickets.detail.requestingUserConfirmation': 'Requesting user confirmation',
  'tickets.detail.approvals': 'Approvals',
  'tickets.detail.step': 'Step',
  'tickets.detail.commentOptional': 'Comment (optional)',
  'tickets.detail.approve': 'Approve',
  'tickets.detail.reject': 'Reject',
  'tickets.detail.tags': 'Tags',
  'tickets.detail.createdAt': 'Created:',
  'tickets.detail.updatedAt': 'Updated:',
  'tickets.detail.attachments': 'Attachments',
  'tickets.detail.openAttachment': 'Open attachment',
  'tickets.detail.attachmentAlt': 'Ticket attachment',
  // Tickets - enums
  'tickets.status.Pendiente': 'Pending',
  'tickets.status.EnProgreso': 'In Progress',
  'tickets.status.Resuelto': 'Resolved',
  'tickets.status.Cerrado': 'Closed',
  'tickets.priority.Baja': 'Low',
  'tickets.priority.Media': 'Medium',
  'tickets.priority.Alta': 'High',
  'tickets.priority.Urgente': 'Urgent',
    
    // Maintenance
    'maintenance.title': 'Maintenance Management',
    'maintenance.subtitle': 'Schedule and manage vehicle maintenance',
    'maintenance.newMaintenance': 'New Maintenance',
    'maintenance.vehicle': 'Vehicle',
    'maintenance.type': 'Type',
    'maintenance.technician': 'Technician',
    'maintenance.cost': 'Cost',
    'maintenance.totalCost': 'Total Cost',
    'maintenance.partsUsed': 'Parts Used',
    'maintenance.preventive': 'Preventive',
    'maintenance.corrective': 'Corrective',
    'maintenance.emergency': 'Emergency',
    'maintenance.scheduled': 'Scheduled',
    'maintenance.completed': 'Completed',
    'maintenance.overdue': 'Overdue',
    // Cleaning
    'cleaning.report': 'Report',
    'cleaning.status.COMPLETED': 'Completed',
    'cleaning.status.PARTIAL': 'Partial',
    'cleaning.status.PENDING': 'Pending',
    'cleaning.date': 'Date',
    'cleaning.timeSpent': 'Time spent',
    'cleaning.responsible': 'Responsible',
    'cleaning.completedTasks': 'Completed tasks',
    'cleaning.problemsFound': 'Issues found',
    'cleaning.observations': 'Observations',
    'cleaning.noTasks': 'No tasks registered.',
    'cleaning.viewDetails': 'View details',
    'cleaning.editReport': 'Edit report',

    // Maintenance detail extras
    'maintenance.detail': 'Maintenance detail',
    'maintenance.currentStatus': 'Current status',
    'maintenance.interventionType': 'Intervention type',
    'maintenance.responsibleTechnician': 'Responsible technician',
    'maintenance.scheduleBlock': 'Schedule',
    'maintenance.scheduledAt': 'Scheduled',
    'maintenance.lastUpdate': 'Last update',
    'maintenance.createdAt': 'Created',
    'maintenance.noVehicle': 'No vehicle data',
    'maintenance.notAssigned': 'Unassigned',
    'maintenance.noDescription': 'No description provided.',
    'maintenance.noParts': 'No parts registered.',
  };

  const spanishTranslations: Record<string, string> = {
    // Common
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Eliminar',
    'common.add': 'Agregar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.status': 'Estado',
    'common.actions': 'Acciones',
    'common.date': 'Fecha',
    'common.time': 'Hora',
    'common.description': 'Descripción',
    'common.priority': 'Prioridad',
    'common.category': 'Categoría',
    'common.loading': 'Cargando...',
    'common.submit': 'Enviar',
    'common.close': 'Cerrar',
    'common.view': 'Ver',
    'common.details': 'Detalles',
    'common.viewDetails': 'Ver Detalles',
    'common.name': 'Nombre',
    'common.email': 'Correo Electrónico',
    'common.role': 'Rol',
    'common.area': 'Área',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.all': 'Todos',
    'common.yes': 'Sí',
    'common.no': 'No',
    'common.confirm': 'Confirmar',
  'common.saving': 'Guardando…',
  'common.creating': 'Creando…',
  'common.title': 'Título',
    
    // Login
    'login.title': 'Iniciar Sesión',
    'login.subtitle': 'Sistema de Gestión Empresarial',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.signIn': 'Iniciar Sesión',
    'login.signingIn': 'Iniciando Sesión...',
    'login.demoAccounts': 'Cuentas de Demostración',
    'login.invalidCredentials': 'Credenciales inválidas',
    
    // Navigation
  'nav.dashboard': 'Panel Principal',
  'nav.inventory': 'Inventario Taller',
  'nav.itInventory': 'Inventario IT',
    'nav.tripReports': 'Reportes de Viajes',
    'nav.routeManagement': 'Gestión de Rutas',
    'nav.fleetRegistry': 'Registro de Flota',
    'nav.maintenance': 'Mantenimiento',
    'nav.cleaningReports': 'Reportes de Limpieza',
    'nav.civilWorks': 'Obras Civiles',
    'nav.tickets': 'Sistema de Tickets',
  'nav.notifications': 'Notificaciones',
  'nav.fuel': 'Combustible',
  'nav.routes': 'Rutas',
  'nav.assignments': 'Asignación Rutas',
  'nav.incidents': 'Incidentes',
    'nav.userManagement': 'Gestión de Usuarios',
  'nav.bukUsers': 'Usuarios Buk',
    'nav.logout': 'Cerrar Sesión',
  'sidebar.logout': 'Cerrar Sesión',
  'sidebar.sessionActive': 'Sesión activa',
  'sidebar.brandSubtitle': 'Operaciones',

    // Buk integration
    'buk.title': 'Directorio Buk',
    'buk.description': 'Listado sincronizado desde Buk mediante n8n.',
    'buk.refresh': 'Actualizar datos',
    'buk.total': 'Usuarios totales',
    'buk.empty': 'Aún no hay usuarios disponibles.',
    'buk.error': 'Error al cargar Buk',
    'buk.columns.id': 'ID',
    'buk.columns.name': 'Nombre',
    'buk.columns.email': 'Correo',
    'buk.columns.personId': 'ID persona',
    'buk.columns.status': 'Estado',
    'buk.endpointLabel': 'Endpoint',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    
    // Tickets
    'tickets.title': 'Sistema de Tickets',
    'tickets.subtitle': 'Gestiona solicitudes de soporte y seguimiento de tareas',
    'tickets.newTicket': 'Nuevo Ticket',
    'tickets.createNew': 'Crear Nuevo Ticket',
    'tickets.submitRequest': 'Envía una nueva solicitud de soporte o ticket',
    'tickets.title_field': 'Título',
    'tickets.category': 'Categoría',
    'tickets.priority': 'Prioridad',
    'tickets.description': 'Descripción',
    'tickets.attachments': 'Adjuntos',
    'tickets.totalTickets': 'Total Tickets',
    'tickets.pending': 'Pendientes',
    'tickets.inProgress': 'En Progreso',
    'tickets.resolved': 'Resueltos',
  // Tickets - extendido
  'tickets.helpdesk': 'Mesa de ayuda',
  'tickets.header': 'Seguimiento centralizado de tickets corporativos',
  'tickets.headerSub': 'Orquesta solicitudes internas, prioriza según criticidad y mantén a cada área informada dentro del nuevo panel colaborativo.',
  'tickets.totalActiveSuffix': 'ticket(s) activos en total',
  'tickets.countSuffix': 'ticket(s)',
  'tickets.syncing': 'Sincronizando tickets…',
  'tickets.noResultsTitle': 'No hay tickets con los criterios actuales',
  'tickets.noResultsHint': 'Ajusta filtros o registra un nuevo ticket para comenzar.',
  'tickets.panel.filters': 'Panel de filtros',
  'tickets.matchesSuffix': 'tickets coinciden con los criterios.',
  'tickets.noMatches': 'Sin coincidencias, ajusta los criterios para continuar.',
  'tickets.view.kanban': 'Kanban',
  'tickets.view.list': 'Lista',
  'tickets.filters.searchPlaceholder': 'Buscar por título, descripción o ID',
  'tickets.filters.reset': 'Restablecer filtros',
  'tickets.unassigned': 'Sin asignar',
  'tickets.noDate': 'Sin fecha',
  'tickets.review': 'Revisar',
  'tickets.emptyColumn': 'Nada por aquí todavía.',
  'tickets.table.id': 'ID',
  'tickets.table.title': 'Título',
  'tickets.table.status': 'Estado',
  'tickets.table.priority': 'Prioridad',
  'tickets.table.category': 'Categoría',
  'tickets.table.assigned': 'Asignado',
  'tickets.table.updated': 'Actualizado',
  'tickets.noTableItems': 'No hay tickets para mostrar con los filtros actuales.',
  // Tickets - KPIs
  'tickets.kpis.inProgressSome': 'Coordinando equipos asignados',
  'tickets.kpis.inProgressNone': 'No hay tickets en ejecución',
  'tickets.kpis.urgentLabel': 'Urgentes',
  'tickets.kpis.urgentSome': 'Prioriza estos casos críticos',
  'tickets.kpis.urgentNone': 'Sin alertas críticas',
  'tickets.kpis.totalInInboxSuffix': 'totales en la bandeja',
  // Tickets - detalle
  'tickets.detail.ticket': 'Ticket',
  'tickets.detail.status': 'Estado',
  'tickets.detail.priority': 'Prioridad',
  'tickets.detail.category': 'Categoría',
  'tickets.detail.assignTo': 'Asignar a',
  'tickets.detail.assign': 'Asignar',
  'tickets.detail.assigning': 'Asignando…',
  'tickets.detail.createdBy': 'Creado por',
  'tickets.detail.assignedTo': 'Asignado a',
  'tickets.detail.recipientAreas': 'Áreas destinatarias',
  'tickets.detail.assignedUserConfirmation': 'Confirmación usuario asignado',
  'tickets.detail.requestingUserConfirmation': 'Confirmación usuario solicitante',
  'tickets.detail.approvals': 'Aprobaciones',
  'tickets.detail.step': 'Paso',
  'tickets.detail.commentOptional': 'Comentario (opcional)',
  'tickets.detail.approve': 'Aprobar',
  'tickets.detail.reject': 'Rechazar',
  'tickets.detail.tags': 'Tags',
  'tickets.detail.createdAt': 'Creado:',
  'tickets.detail.updatedAt': 'Actualizado:',
  'tickets.detail.attachments': 'Adjuntos',
  'tickets.detail.openAttachment': 'Abrir adjunto',
  'tickets.detail.attachmentAlt': 'Adjunto del ticket',
  // Tickets - enums
  'tickets.status.Pendiente': 'Pendiente',
  'tickets.status.EnProgreso': 'En Progreso',
  'tickets.status.Resuelto': 'Resuelto',
  'tickets.status.Cerrado': 'Cerrado',
  'tickets.priority.Baja': 'Baja',
  'tickets.priority.Media': 'Media',
  'tickets.priority.Alta': 'Alta',
  'tickets.priority.Urgente': 'Urgente',
    
    // Maintenance
    'maintenance.title': 'Gestión de Mantenimiento',
    'maintenance.subtitle': 'Programa y gestiona mantenimientos de vehículos',
    'maintenance.newMaintenance': 'Nuevo Mantenimiento',
    'maintenance.vehicle': 'Vehículo',
    'maintenance.type': 'Tipo',
    'maintenance.technician': 'Técnico',
    'maintenance.cost': 'Costo',
    'maintenance.totalCost': 'Costo Total',
    'maintenance.partsUsed': 'Repuestos Utilizados',
    'maintenance.preventive': 'Preventivo',
    'maintenance.corrective': 'Correctivo',
    'maintenance.emergency': 'Emergencia',
    'maintenance.scheduled': 'Programados',
    'maintenance.completed': 'Completados',
    'maintenance.overdue': 'Vencidos',
    // Cleaning
    'cleaning.report': 'Reporte',
    'cleaning.status.COMPLETED': 'Completado',
    'cleaning.status.PARTIAL': 'Parcial',
    'cleaning.status.PENDING': 'Pendiente',
    'cleaning.date': 'Fecha',
    'cleaning.timeSpent': 'Tiempo invertido',
    'cleaning.responsible': 'Responsable',
    'cleaning.completedTasks': 'Tareas completadas',
    'cleaning.problemsFound': 'Problemas encontrados',
    'cleaning.observations': 'Observaciones',
    'cleaning.noTasks': 'Sin tareas registradas.',
    'cleaning.viewDetails': 'Ver detalles',
    'cleaning.editReport': 'Editar reporte',

    // Maintenance detail extras
    'maintenance.detail': 'Detalle de mantenimiento',
    'maintenance.currentStatus': 'Estado actual',
    'maintenance.interventionType': 'Tipo de intervención',
    'maintenance.responsibleTechnician': 'Técnico responsable',
    'maintenance.scheduleBlock': 'Programación',
    'maintenance.scheduledAt': 'Programada',
    'maintenance.lastUpdate': 'Última actualización',
    'maintenance.createdAt': 'Creada',
    'maintenance.noVehicle': 'Sin datos de vehículo',
    'maintenance.notAssigned': 'No asignado',
    'maintenance.noDescription': 'Sin descripción registrada.',
    'maintenance.noParts': 'No se registraron repuestos.',
  };

  const portugueseTranslations: Record<string, string> = {
    // Common
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.edit': 'Editar',
    'common.delete': 'Excluir',
    'common.add': 'Adicionar',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.status': 'Status',
    'common.actions': 'Ações',
    'common.date': 'Data',
    'common.time': 'Hora',
    'common.description': 'Descrição',
    'common.priority': 'Prioridade',
    'common.category': 'Categoria',
    'common.loading': 'Carregando...',
    'common.submit': 'Enviar',
    'common.close': 'Fechar',
    'common.view': 'Ver',
    'common.details': 'Detalhes',
    'common.viewDetails': 'Ver Detalhes',
    'common.name': 'Nome',
    'common.email': 'E-mail',
    'common.role': 'Função',
    'common.area': 'Área',
    'common.active': 'Ativo',
    'common.inactive': 'Inativo',
    'common.all': 'Todos',
    'common.yes': 'Sim',
    'common.no': 'Não',
    'common.confirm': 'Confirmar',
  'common.saving': 'Salvando…',
  'common.creating': 'Criando…',
  'common.title': 'Título',

    // Login
    'login.title': 'Acessar',
    'login.subtitle': 'Sistema de Gestão Empresarial',
    'login.email': 'E-mail',
    'login.password': 'Senha',
    'login.signIn': 'Entrar',
    'login.signingIn': 'Entrando...',
    'login.demoAccounts': 'Contas de Demonstração',
    'login.invalidCredentials': 'Credenciais inválidas',

    // Navigation
    'nav.dashboard': 'Painel',
    'nav.tripReports': 'Relatórios de Viagem',
    'nav.routeManagement': 'Gestão de Rotas',
    'nav.fleetRegistry': 'Registro de Frotas',
    'nav.maintenance': 'Manutenção',
    'nav.cleaningReports': 'Relatórios de Limpeza',
    'nav.civilWorks': 'Obras Civis',
    'nav.tickets': 'Sistema de Chamados',
    'nav.notifications': 'Notificações',
    'nav.fuel': 'Combustível',
    'nav.routes': 'Rotas',
    'nav.assignments': 'Designações de Rotas',
    'nav.incidents': 'Incidentes',
    'nav.userManagement': 'Gestão de Usuários',
    'nav.bukUsers': 'Usuários Buk',
    'nav.logout': 'Sair',
    'sidebar.logout': 'Encerrar sessão',
    'sidebar.sessionActive': 'Sessão ativa',
    'sidebar.brandSubtitle': 'Operações',

    // Buk integration
    'buk.title': 'Diretório Buk',
    'buk.description': 'Lista sincronizada do Buk via n8n.',
    'buk.refresh': 'Atualizar dados',
    'buk.total': 'Total de usuários',
    'buk.empty': 'Ainda não há usuários disponíveis.',
    'buk.error': 'Erro ao carregar Buk',
    'buk.columns.id': 'ID',
    'buk.columns.name': 'Nome',
    'buk.columns.email': 'E-mail',
    'buk.columns.personId': 'ID pessoa',
    'buk.columns.status': 'Status',
    'buk.endpointLabel': 'Endpoint',
      'buk.columns.registration': 'Account',
      'buk.actions.register': 'Register',
      'buk.actions.registering': 'Registering…',
      'buk.actions.registered': 'Already registered',
      'buk.actions.registerSuccess': 'Request sent to create account',
      'buk.actions.registerError': 'Error sending request',
      'buk.pagination.showing': 'Showing',
      'buk.pagination.of': 'of',
      'buk.pagination.previous': 'Previous',
      'buk.pagination.next': 'Next',
      'buk.pagination.empty': 'No records to display',
      'buk.columns.registration': 'Cuenta',
      'buk.actions.register': 'Registrar',
      'buk.actions.registering': 'Registrando…',
      'buk.actions.registered': 'Ya existe',
      'buk.actions.registerSuccess': 'Solicitud enviada para crear cuenta',
      'buk.actions.registerError': 'Error al enviar la solicitud',
      'buk.pagination.showing': 'Mostrando',
      'buk.pagination.of': 'de',
      'buk.pagination.previous': 'Anterior',
      'buk.pagination.next': 'Siguiente',
      'buk.pagination.empty': 'Sin registros para mostrar',
      'buk.columns.registration': 'Conta',
      'buk.actions.register': 'Registrar',
      'buk.actions.registering': 'Registrando…',
      'buk.actions.registered': 'Já existe',
      'buk.actions.registerSuccess': 'Solicitação enviada para criar conta',
      'buk.actions.registerError': 'Erro ao enviar a solicitação',
      'buk.pagination.showing': 'Mostrando',
      'buk.pagination.of': 'de',
      'buk.pagination.previous': 'Anterior',
      'buk.pagination.next': 'Próximo',
      'buk.pagination.empty': 'Sem registros para exibir',

    // Dashboard
    'dashboard.welcome': 'Bem-vindo',

    // Tickets
    'tickets.title': 'Sistema de Chamados',
    'tickets.subtitle': 'Gerencie solicitações de suporte e acompanhamento de tarefas',
    'tickets.newTicket': 'Novo Chamado',
    'tickets.createNew': 'Criar Novo Chamado',
    'tickets.submitRequest': 'Envie uma nova solicitação de suporte ou chamado',
    'tickets.title_field': 'Título',
    'tickets.category': 'Categoria',
    'tickets.priority': 'Prioridade',
    'tickets.description': 'Descrição',
    'tickets.attachments': 'Anexos',
    'tickets.totalTickets': 'Total de Chamados',
    'tickets.pending': 'Pendentes',
    'tickets.inProgress': 'Em Andamento',
    'tickets.resolved': 'Resolvidos',
  // Tickets - extendido
  'tickets.helpdesk': 'Central de Ajuda',
  'tickets.header': 'Acompanhamento centralizado de chamados corporativos',
  'tickets.headerSub': 'Orquestre solicitações internas, priorize por criticidade e mantenha cada área informada no novo painel colaborativo.',
  'tickets.totalActiveSuffix': 'chamado(s) ativos no total',
  'tickets.countSuffix': 'chamado(s)',
  'tickets.syncing': 'Sincronizando chamados…',
  'tickets.noResultsTitle': 'Sem chamados com os critérios atuais',
  'tickets.noResultsHint': 'Ajuste os filtros ou crie um novo chamado para começar.',
  'tickets.panel.filters': 'Painel de filtros',
  'tickets.matchesSuffix': 'chamados correspondem aos critérios.',
  'tickets.noMatches': 'Sem correspondências, ajuste os critérios para continuar.',
  'tickets.view.kanban': 'Kanban',
  'tickets.view.list': 'Lista',
  'tickets.filters.searchPlaceholder': 'Buscar por título, descrição ou ID',
  'tickets.filters.reset': 'Redefinir filtros',
  'tickets.unassigned': 'Não atribuído',
  'tickets.noDate': 'Sem data',
  'tickets.review': 'Revisar',
  'tickets.emptyColumn': 'Nada aqui ainda.',
  'tickets.table.id': 'ID',
  'tickets.table.title': 'Título',
  'tickets.table.status': 'Status',
  'tickets.table.priority': 'Prioridade',
  'tickets.table.category': 'Categoria',
  'tickets.table.assigned': 'Atribuído',
  'tickets.table.updated': 'Atualizado',
  'tickets.noTableItems': 'Sem chamados para exibir com os filtros atuais.',
  // Tickets - KPIs
  'tickets.kpis.inProgressSome': 'Coordenando equipes atribuídas',
  'tickets.kpis.inProgressNone': 'Sem chamados em execução',
  'tickets.kpis.urgentLabel': 'Urgentes',
  'tickets.kpis.urgentSome': 'Priorize estes casos críticos',
  'tickets.kpis.urgentNone': 'Sem alertas críticos',
  'tickets.kpis.totalInInboxSuffix': 'no total na caixa de entrada',
  // Tickets - detalhe
  'tickets.detail.ticket': 'Chamado',
  'tickets.detail.status': 'Status',
  'tickets.detail.priority': 'Prioridade',
  'tickets.detail.category': 'Categoria',
  'tickets.detail.assignTo': 'Atribuir a',
  'tickets.detail.assign': 'Atribuir',
  'tickets.detail.assigning': 'Atribuindo…',
  'tickets.detail.createdBy': 'Criado por',
  'tickets.detail.assignedTo': 'Atribuído a',
  'tickets.detail.recipientAreas': 'Áreas destinatárias',
  'tickets.detail.assignedUserConfirmation': 'Confirmação do usuário atribuído',
  'tickets.detail.requestingUserConfirmation': 'Confirmação do usuário solicitante',
  'tickets.detail.approvals': 'Aprovações',
  'tickets.detail.step': 'Passo',
  'tickets.detail.commentOptional': 'Comentário (opcional)',
  'tickets.detail.approve': 'Aprovar',
  'tickets.detail.reject': 'Rejeitar',
  'tickets.detail.tags': 'Tags',
  'tickets.detail.createdAt': 'Criado:',
  'tickets.detail.updatedAt': 'Atualizado:',
  // Tickets - enums
  'tickets.status.Pendiente': 'Pendente',
  'tickets.status.EnProgreso': 'Em Andamento',
  'tickets.status.Resuelto': 'Resolvido',
  'tickets.status.Cerrado': 'Fechado',
  'tickets.priority.Baja': 'Baixa',
  'tickets.priority.Media': 'Média',
  'tickets.priority.Alta': 'Alta',
  'tickets.priority.Urgente': 'Urgente',

    // Maintenance
    'maintenance.title': 'Gestão de Manutenção',
    'maintenance.subtitle': 'Agende e gerencie a manutenção da frota',
    'maintenance.newMaintenance': 'Nova Manutenção',
    'maintenance.vehicle': 'Veículo',
    'maintenance.type': 'Tipo',
    'maintenance.technician': 'Técnico',
    'maintenance.cost': 'Custo',
    'maintenance.totalCost': 'Custo Total',
    'maintenance.partsUsed': 'Peças Utilizadas',
    'maintenance.preventive': 'Preventiva',
    'maintenance.corrective': 'Corretiva',
    'maintenance.emergency': 'Emergencial',
    'maintenance.scheduled': 'Programada',
    'maintenance.completed': 'Concluída',
    'maintenance.overdue': 'Atrasada',
    // Cleaning
    'cleaning.report': 'Relatório',
    'cleaning.status.COMPLETED': 'Concluído',
    'cleaning.status.PARTIAL': 'Parcial',
    'cleaning.status.PENDING': 'Pendente',
    'cleaning.date': 'Data',
    'cleaning.timeSpent': 'Tempo investido',
    'cleaning.responsible': 'Responsável',
    'cleaning.completedTasks': 'Tarefas concluídas',
    'cleaning.problemsFound': 'Problemas encontrados',
    'cleaning.observations': 'Observações',
    'cleaning.noTasks': 'Sem tarefas registradas.',
    'cleaning.viewDetails': 'Ver detalhes',
    'cleaning.editReport': 'Editar relatório',

    // Maintenance detail extras
    'maintenance.detail': 'Detalhe de manutenção',
    'maintenance.currentStatus': 'Status atual',
    'maintenance.interventionType': 'Tipo de intervenção',
    'maintenance.responsibleTechnician': 'Técnico responsável',
    'maintenance.scheduleBlock': 'Programação',
    'maintenance.scheduledAt': 'Programada',
    'maintenance.lastUpdate': 'Última atualização',
    'maintenance.createdAt': 'Criada',
    'maintenance.noVehicle': 'Sem dados do veículo',
    'maintenance.notAssigned': 'Não atribuído',
    'maintenance.noDescription': 'Sem descrição registrada.',
    'maintenance.noParts': 'Sem peças registradas.',
  };

  const translations: Record<Languages, Record<string, string>> = {
    en: englishTranslations,
    es: spanishTranslations,
    pt: portugueseTranslations,
    fr: englishTranslations,
    de: englishTranslations,
    it: englishTranslations,
  };

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Languages>('es');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Languages | null;
    if (savedLanguage && ['en', 'es', 'pt', 'fr', 'de', 'it'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Persistir cambios de idioma
  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = useCallback((key: string) => translations[language][key] ?? key, [language]);

  const value = useMemo(() => ({ t, language, setLanguage }), [t, language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};