###Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"john@example.com",
    "password":"admin123"
}

### Create Vehiculo
POST http://localhost:3000/vehiculo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc2MDMwNzUsImV4cCI6MTc1NzYwMzM3NX0.nfyQVwP3Smf8Ll7XiqStwlKE5s7Os048s2sn2pHtIa4

{
    "patente":"BXVP-30",
    "capacidad":20000,
    "odometro":13980,
    "estado": "disponible"
}

### alls  Vehiculo
GET http://localhost:3000/vehiculo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTYyOTMsImV4cCI6MTc1NzU1NjU5M30.yvkCX5SFDB4C6cNdemacO4ojIy8UBKUEqEGj6DXDyFU

### alls  Vehiculo
GET http://localhost:3000/vehiculo/BXVP-39
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTU5ODQsImV4cCI6MTc1NzU1NjI4NH0.6VAJydqcz1t0WLEMi5fJIB7r7xskQawsoPHI-BOvhLk

### patch Vehiculo
PATCH  http://localhost:3000/vehiculo/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTU5ODQsImV4cCI6MTc1NzU1NjI4NH0.6VAJydqcz1t0WLEMi5fJIB7r7xskQawsoPHI-BOvhLk

{
    "estado":"en_mantenimiento"
}

### patch Vehiculo
DELETE   http://localhost:3000/vehiculo/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1MzUzNTQsImV4cCI6MTc1NzUzNTY1NH0.F5-3RYRpDclukdgsS-2KKPW4USbVmOaFWpsM1WIfv4Q

### patch Vehiculo Estado
PATCH    http://localhost:3000/vehiculo/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTU5ODQsImV4cCI6MTc1NzU1NjI4NH0.6VAJydqcz1t0WLEMi5fJIB7r7xskQawsoPHI-BOvhLk

{
    "estado":"en_mantenimiento"
}

### patch Vehiculo Estado
POST  http://localhost:3000/vehiculo/5/documentos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZXhhbXBsZS5jb20iLCJzdWIiOjEsInJvbGVzIjpbIkFkbWluIl0sInBlcm1pc3Npb25zIjpbIlZJRVdfREFTSEJPQVJEIiwiVklFV19USUNLRVRTIiwiTUFOQUdFX1RJQ0tFVFMiLCJWSUVXX1RSSVBfUkVQT1JUUyIsIk1BTkFHRV9UUklQX1JFUE9SVFMiLCJWSUVXX1JPVVRFUyIsIk1BTkFHRV9ST1VURVMiLCJWSUVXX0ZMRUVUIiwiTUFOQUdFX0ZMRUVUIiwiVklFV19NQUlOVEVOQU5DRSIsIk1BTkFHRV9NQUlOVEVOQU5DRSIsIlZJRVdfQ0lWSUxfV09SS1MiLCJNQU5BR0VfQ0lWSUxfV09SS1MiLCJWSUVXX0NMRUFOSU5HX1JFUE9SVFMiLCJNQU5BR0VfQ0xFQU5JTkdfUkVQT1JUUyJdLCJpYXQiOjE3NTc1NTYyOTMsImV4cCI6MTc1NzU1NjU5M30.yvkCX5SFDB4C6cNdemacO4ojIy8UBKUEqEGj6DXDyFU

{
    "tipo": "pdf",
    "url": "local:asda",
    "descripcion": "documento" 
}


