name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: Find backend directory
        id: find-backend
        run: |
          echo "Buscando package.json..."
          PACKAGE_PATHS=$(find . -name "package.json" -type f | grep -v "node_modules")
          echo "Encontrados:"
          echo "$PACKAGE_PATHS"
          
          # Tomar el primero que no esté en node_modules
          BACKEND_DIR=$(echo "$PACKAGE_PATHS" | head -1 | xargs dirname)
          echo "BACKEND_DIR=$BACKEND_DIR" >> $GITHUB_ENV
          echo "Usando directorio: $BACKEND_DIR"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Navigate to backend directory
        run: |
          echo "Cambiando a directorio: $BACKEND_DIR"
          cd "$BACKEND_DIR"
          echo "Directorio actual: $(pwd)"
          ls -la

      - name: Install backend dependencies
        run: |
          cd "$BACKEND_DIR"
          npm install

      - name: Generate Prisma Client
        run: |
          cd "$BACKEND_DIR"
          npx prisma generate

      - name: Run backend linter
        run: |
          cd "$BACKEND_DIR"
          npm run lint || echo "Linter no configurado"

      - name: Run backend tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
        run: |
          cd "$BACKEND_DIR"
          npm test

      - name: Build backend
        run: |
          cd "$BACKEND_DIR"
          npm run build
